### PR TITLE
fix: leave semicolons in comments

### PR DESCRIPTION
**Pull request by alexanderczigler**

### CODE REVIEW

**Comment by believer** [comment]
What does it fix, just seems like some cleaner docs? 🤔

**Comment by alexanderczigler** [comment]
If you have a semicolon in the `doc` field of an avro schema, it gets removed when the typescript is generated.

## Example

### Source AVSC

```json
{
    "name": "id",
    "type": "string",
    "doc": "Unique identifier of the instrument, consists of ISIN, MIC and Currency Code. Format: ISIN;MIC;CurrencyCode"
},
```

### Resulting ts

```typescript
export interface StockTicker {
  /**
   * Unique identifier of the instrument, consists of ISIN, MIC and Currency Code. Format: ISINMICCurrencyCode
   */
  id: string
}
```

**Review by believer — APPROVED** [review]
Ahh I see, that's a nice use case. Thanks for the clarification!

**Comment by alexanderczigler** [comment]
Thanks!

**Pull request merged**
